export const data = [
    {
      question: "Which of the following is the most recent framework?",
      option1: "JavaScript",
      option2: "Angular",
      option3: "React",
      option4: "TypeScript",
      ans: 3,
    },
    {
      question: "First page of Website is termed as?",
      option1: "Index Page",
      option2: "Homepage",
      option3: "Sitemap",
      option4: "Pen Drive",
      ans: 2,
    },
    {
      question: "What does HTML stand for?",
      option1: "Hyper Trainer Marking Language",
      option2: "Hyper Text Marketing Language",
      option3: "Hyper Text Markup Leveler",
      option4: "Hyper Text Markup Language",
      ans: 4,
    },
    {
      question: "<h1>Text</h1> is the correct way of making a header in HTML.",
      option1: "True",
      option2: "False",
      ans: 1,
    },
    {
      question: "What does CSS stand for?",
      option1: "Cascading Style Sheets",
      option2: "Creative Style Sheets",
      option3: "Computer Style Sheets",
      option4: "Colorful Style Sheets",
      ans: 1,
    },
  ];